
FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    curl \
    gnupg \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Копируйте файлы приложения
COPY . .

# Установите необходимые библиотеки
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Устанавливаем переменную окружения
ENV GOOGLE_APPLICATION_CREDENTIALS="/app/tfm-edem-54bbbe821339.json"



# Открываем порт
EXPOSE 8080

# Запуск приложения
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]


