- name: ml_clusterizacion
  schema: 
    - name: "customer_id"
      type: "STRING"
      mode: "REQUIRED"
    - name: "total_spent"
      type: "FLOAT"
      mode: "NULLABLE"
    - name: "purchase_frequency"
      type: "FLOAT"
      mode: "NULLABLE"
    - name: "average_order_value"
      type: "FLOAT"
      mode: "NULLABLE"
    - name: "num_reviews"
      type: "FLOAT"
      mode: "NULLABLE"
    - name: "avg_review_score"
      type: "FLOAT"
      mode: "NULLABLE"
    - name: "days_since_purchase"
      type: "FLOAT"
      mode: "NULLABLE"
